### ISSUE TITLE
PPCs for time series

### ISSUE THREAD

**Issue by jgabry** [jgabry/ppcheck#5]

**Comment by jgabry** [comment]
added preliminary versions in 59bb9df4817d73f9612c77f879678ee6c29cf3fb

**Comment by paul-buerkner** [comment]
The `ppc_ts` function looks good to me. I have one suggestions though. I appears that `colnames(yrep)` is also used as a sort of "time" variable in the sense that specifiying `colnames(yrep) <- sample(1:ncol(yrep))` can completely distort the plot, presumably because `yrep` is sorted after colnames. Is this intentional?

**Comment by paul-buerkner** [comment]
It has been fixed now! :-)

**Comment by jgabry** [comment]
Ok cool thanks
